spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect #mysql sql문 형식으로 로그에 출력해줌
  profiles:
    include: oauth
  h2:
    console:
      enabled: true
  session:
    store-type: jdbc
logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace