spring:
  jpa:
    show-sql: true
  datasource:
    url: jdbc:mysql://localhost:3306/book?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  profiles:
    group:
      local-real: local-real, oauth
      real: real, real-db, oauth
      real1: real1, real-db, oauth
      real2: real2, real-db, oauth
  session:
    store-type: jdbc
jackson:
  property-naming-strategy: SNAKE_CASE

logging:
  level:
    root: info
    com.zaxxer.hikari.HikariConfig: debug
    org.hibernate.SQL: debug
    hibernate.type.descriptor.sql.BasicBinder: trace